### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws_ses#1]
Hey @lessless, per https://elixirforum.com/t/proposal-exaws-2-0/9269 the ExAws project is splitting out each service into its own project.

You are a major contributor to the SES service in ExAws. If you wish to be its maintainer, please let me know and I will give you commit access to this repository. If you do not want this, let me know and I will look for someone else.

Thank you!

**Comment by lessless** [comment]
Hi @benwilson512 ,

I would love to!

**Comment by benwilson512** [comment]
Thank you! You have been given write access to this repository.
