### ISSUE TITLE
Release 2.3 on Hex

### ISSUE THREAD

**Issue by kreba** [ex-aws/ex_aws_ses#18]
The most recent release available from Hex is 2.1.1.

Please release the current version to Hex.

Thank you in advance!

**Comment by Klohto** [comment]
Friendly bump, would be nice to get this released :)

**Comment by lessless** [comment]
Sorry for the delay folks. It's up now, please give it a try and feel free to close the issue if everything is ok!

**Comment by Klohto** [comment]
Damn, running smooth. Thanks for the update!

**Comment by kreba** [comment]
Looks good to me, thanks a lot!
