### ISSUE TITLE
Does this library support throttling / rate limiting?

### ISSUE THREAD

**Issue by travelmassive** [ex-aws/ex_aws_ses#19]
Apologies if this is the wrong place to ask.

I'm getting a "Maximum sending rate exceeded." error from AWS SES when sending ~1000 notifications or so.

Does this library support rate throttling, or do I need to look further upstream (eg. Bamboo mailer) for this functionality (or do I need to implement myself?)

Thanks in advance for any tips / advice.

-- Ian

**Comment by lessless** [comment]
Hi Ian,

Throttling is not a part of this library because every user would have its own limits and may use different strategies to circumvent them. 

The better place to ask this question is an Elixir forum - you can get more practical responses there.

Cheers

**Comment by travelmassive** [comment]
Thanks for the answer. I kinda disagree that every user would have different strategies. AWS SES has a maximum sending rate (emails per second) so really that's the only strategy to adhere to. - Ian

**Comment by lessless** [comment]
They also limit the number of emails per 24 hours, but I'm talking about things like account and region rotation, for example. 
That was the scenario that I started with. So hence I needed as much control as possible. 

But you're right that it's probably required by the minority of users, so if you feel like submitting a PR that would provide that as an optional feature, I'm keen to review it. 

It might be a layer on top of the existing functionality, for example.

**Comment by travelmassive** [comment]
Got it. The challenge is "where" do you put throttling in a typical Elixir app?

For my Phoenix app, I have no less than 5 elixir libraries between my app and SES, in this order (I think).

my_app -> bamboo_phoenix -> bamboo -> bamboo_ses -> ex_aws_ses -> ex_aws-> (AWS SES)

Ideally I'd like to implement a very simple rate limit solution that others can easily replicate.

**Comment by lessless** [comment]
That's tough! 

Are you using SES templates? How is it important that every customer get their email (i.e. do you need retries)?

**Comment by travelmassive** [comment]
Not using SES templates. The emails are personalised notifications about topics the user is subscribed to (alerting to a new post on our site), so not a big deal if a few get dropped (but prefer to send them all, obviously).

**Comment by lessless** [comment]
One of the quickest solutions would be throwing a rate-limiting library between your app and an email library, something like https://github.com/ExHammer/hammer might work.
