### ISSUE TITLE
:list_identities Parser Response Incorrect key definition

### ISSUE THREAD

**Issue by LetThereBeDwight** [ex-aws/ex_aws_ses#22]
In `lib/ex_aws/ses/parsers.ex` the `parse` method defined for `:list_identities` seems to correctly parse the results, but it puts them under the key `custom_verification_templates` when that key should most likely be `identities`. A simple enough fix here in the library but something that may break existing workflows.

**Comment by lessless** [comment]
maybe we can duplicate the output and put `custom_verification_templates` under `https://hexdocs.pm/elixir/1.7.4/Module.html#module-deprecated` 🤔

**Comment by LetThereBeDwight** [comment]
I can't think of a cute way to do that given that you can't deprecate a key, just the whole function or module. Duplicating the output under the key `identities` makes for a good stop gap to at least stop people from using the incorrect key.

**Comment by lessless** [comment]
> I can't think of a cute way to do that given that you can't deprecate a key, just the whole function or module.

True. My inclination here is to send the message, and if people pay attention to warnings - they will have a chance to take an action. 
Say, dropping `custom_verification_templates` will happen in the six months' time and maybe with a major version bump, the chances to see that message will be relatively high. 

Also, it might be worthy to consult with the community on the forum and maybe learn other better options to do that.

**Comment by LetThereBeDwight** [comment]
> True. My inclination here is to send the message, and if people pay attention to warnings - they will have a chance to take an action. Say, dropping `custom_verification_templates` will happen in the six months' time and maybe with a major version bump, the chances to see that message will be relatively high.

That makes sense to me, and if it's on a major version upgrade bump people will at least be aware that there may be some such breaking changes.

> Also, it might be worthy to consult with the community on the forum and maybe learn other better options to do that.

Agreed

**Comment by LetThereBeDwight** [comment]
A little bit of discussion on the Elixir discord make it seem like that's the way to go, along with adding something like `#TODO: change key :custom_verification_templates to :identities for 3.0` as was done for ExUnit to go up for elixir 2.0  https://github.com/elixir-lang/elixir/issues/5254

**Comment by lessless** [comment]
Cool! Would you like to take a stab?

**Comment by LetThereBeDwight** [comment]
Yea I'll put in a quick PR today or tomorrow.
