### ISSUE TITLE
Allow using JSON encoder at choice

### ISSUE THREAD

**Issue by suppayami** [ex-aws/ex_aws_ses#9]
Allow using JSON encoder at choice for format template

### Environment

* Elixir & Erlang versions (elixir --version):
* ExAws version 2.1
* HTTP client version: hackney 1.15

### Current behavior

The package now uses Poison to format template, hard-coded here https://github.com/ex-aws/ex_aws_ses/blob/master/lib/ex_aws/ses.ex#L287

### Expected behavior

Allows configuring JSON encoder in config OR use JSON encoder defined in ExAws

**Comment by lessless** [comment]
Hi @suppayami ,

Thanks for your suggestion. Won't you mind to submit a PR? 

I guess this feature is already implemented in other exa_aws sub-libraries and they can be a source of inspiration or guidance on how to put it together.

**Comment by suppayami** [comment]
Hi @lessless ,

I will submit a PR in one or two weeks (if no one submit in meantime). Thanks for suggestion :)

**Comment by suppayami** [comment]
Hi @lessless ,

I submitted a PR #10 , if you have time please take a look.

**Comment by lessless** [comment]
thanks @suppayami!

**Comment by lessless** [comment]
I'll cut release later this week

**Comment by RRodd** [comment]
Hello, new to Elixir but found this issue raised and addressed when I experienced this today:

```
==> ex_aws
Compiling 26 files (.ex)
Generated ex_aws app
==> ex_aws_ses
Compiling 2 files (.ex)
warning: Poison.encode!/1 is undefined (module Poison is not available or is yet to be defined)
lib/ex_aws/ses.ex:287: ExAws.SES.format_template_data/1
Generated ex_aws_ses app
```

I guess it needs an updated release to be uploaded to Hex to address the warning with the above PR?  Thanks!
